services:
  postgres:
    image: timescale/timescaledb:latest-pg17
    container_name: trading_sim_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-tradingapp}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-trading_sim}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    container_name: trading_sim_redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redispassword}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispassword} --appendonly yes
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: